site_name: "Grugstream"

theme:
  name: 'material'
  palette:
    scheme: slate
    primary: indigo


plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: numpy
            docstring_options:
              ignore_init_summary: yes
            rendering:
              show_source: true
              show_type_annotations: true

