site_name: "Grugstream"

theme:
  name: 'material'
  palette:
    scheme: slate
    primary: indigo
  features:
    - navigation.tabs
    - navigation.tabs.sticky


plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: numpy
            docstring_options:
              ignore_init_summary: yes
            rendering:
              show_source: true
              show_type_annotations: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - markdown_include.include
